name: example
description: An example app to show the usage of the IntroViewsFlutter package.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intro_views_flutter:
    path: ../
  flutter_staggered_animations: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^0.13.0
  shared_preferences: ^2.0.13
  toast: ^0.1.5
  firebase_database: ^9.0.10
  firebase_core : ^1.14.0
  firebase_database_web: ^0.2.0+9
  firebase_auth: ^3.3.15
  http_parser: ^4.0.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  animated_splash_screen: ^1.2.0
  lottie: ^1.3.0
  date_range_picker: ^1.0.3
  flutter_colored_progress_indicators: ^1.2.0
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android:true
  ios:true
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/air-hostess.png
    - assets/airplane.png
    - assets/bus-driver.png
    - assets/bus.png
    - assets/hotel.png
    - assets/taxi.png
    - assets/taxi-driver.png
    - assets/waiter.png
    - assets/travel.png
    - assets/home.png
    - assets/home1.png
    - assets/login.png
    - assets/register.png
    - assets/images/backgrounds.jpg
    - assets/images/building.jpg
    - assets/images/hotel.jpg
    - assets/images/nature.jpg
    - assets/images/park.jpg
    - assets/images/travel.jpg
    - assets/images/paris.jpg
    - assets/images/murano.jpg
    - assets/images/newdelhi.jpg
    - assets/images/newyork.jpg
    - assets/images/santorini.jpg
    - assets/images/saopaulo.jpg
    - assets/images/venice.jpg
    - assets/images/gondola.jpg
    - assets/images/hotel1.jpg
    - assets/images/hotel0.jpg
    - assets/images/hotel2.jpg
    - assets/images/stmarksbasilica.jpg
    - assets/images/travel_world.json
    - assets/images/avatar.png
    









  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/Fonts/sspu.ttf
    - family: Serif
      fonts:
        - asset: assets/Fonts/PTSerif-Bold.ttf
        - asset: assets/Fonts/PTSerif-BoldItalic.ttf
        - asset: assets/Fonts/PTSerif-Italic.ttf
        - asset: assets/Fonts/PTSerif-Regular.ttf
          weight: 700  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
