name: intro_views_flutter
description: A Flutter package for simple material design app intro screens with some cool animations.
version: 3.2.0
homepage: https://github.com/aagarwal1012/IntroViews-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.11
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.0.0
  get: ^4.6.1
  outline_gradient_button: ^2.0.0+1
  page_transition: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3
